ls:
  .css: camelCase
  .js: camelCase
  .ts: camelCase
  .tsx: camelCase | PascalCase
  .d.tsx: PascalCase
  .json: kebab-case
  .yaml: kebab-case
  src/pages:
    .dir: lowercase

ignore:
  - node_modules
  - out
  - cypress/e2e
  - tests
  - coverage
  - .github
  - .git
  - .next
  - src/pages/_app.tsx
  - src/pages/_document.tsx
  - next-env.d.ts
  - commitlint.config.js
  - lint-staged.config.js
  - next.config.js
  - postcss.config.js
  - prettier.config.js
  - stylelint.config.js
  - tailwind.config.js
  - cypress.config.js
  - jest.config.js
  - jest.setup.js
