ls:
  .css: camelCase
  .js: camelCase
  .config.js: lowercase
  .setup.js: lowercase
  .ts: camelCase | PascalCase
  .cy.ts: camelCase
  .tsx: camelCase | PascalCase
  .test.tsx: camelCase
  .json: kebab-case
  .yaml: kebab-case
  src/pages:
    .dir: lowercase

ignore:
  - node_modules
  - out
  - coverage
  - .github
  - .git
  - .next
  - src/pages/_app.tsx
  - src/pages/_document.tsx
  - next-env.d.ts
