name: deploy-azure-develop

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "18.x"

jobs:
  build-deploy:
    name: Build and Deploy to Azure static Web Apps
    runs-on: ubuntu-latest
    environment: testing
    outputs:
      static_web_app_url: ${{ steps.set-url.outputs.static_web_app_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install

      - name: Build
        run: npm run build-prod

      - name: Deploy to Azure Static WebApp
        id: deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEVELOP }}
          action: "upload"
          app_location: "/out"
          api_location: ""
          output_location: ""
          skip_app_build: true

      - name: Set Azure Static WebApp URL
        id: set-url
        run: echo "STATIC_WEB_APP_URL=${{ steps.deploy.outputs.static_web_app_url }}" >> "$GITHUB_OUTPUT"

  test:
    name: Run e2e Cypress and visual regression Percy tests on Node v18.x
    runs-on: ubuntu-latest
    environment: testing
    needs: build-deploy
    env:
      STATIC_WEB_APP_URL: ${{ needs.build-deploy.outputs.static_web_app_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm install

      - name: Test cypress e2e
        uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: ${{ env.STATIC_WEB_APP_URL}}
          browser: chrome
          record: true
          parallel: true
          command: npx cypress run --config baseUrl=${{ env.STATIC_WEB_APP_URL}}
        env:
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Test cypress percy visual regression
        uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: ${{ env.STATIC_WEB_APP_URL}}
          browser: chrome
          command: npx percy exec -- cypress run --config video=false,screenshotOnRunFailure=false,baseUrl=${{ env.STATIC_WEB_APP_URL}}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
