name: deploy-azure-develop

on:
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "18.x"

jobs:
  build-deploy:
    name: Build and Deploy to Azure static Web Apps
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install

      - name: Build
        run: npm run build-prod

      - name: "Deploy to Azure Static WebApp"
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEVELOP }}
          action: "upload"
          app_location: "/out"
          api_location: ""
          output_location: ""
          skip_app_build: true
