name: deploy-azure-develop-clean

on:
  pull_request:
    types: [closed]
    branches: [main, develop]

jobs:
  clean-up:
    name: Delete Azure Static WebApp pre-production environment
    runs-on: ubuntu-latest
    environment: testing
    env:
      STATIC_WEB_APP_DEPLOYMENT_NAME: "#${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

    steps:
      - name: Delete Azure Static WebApp pre-production environment
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEVELOP }}
          action: "close"
          deployment_environment: ${{ env.STATIC_WEB_APP_DEPLOYMENT_NAME }}
