name: test-e2e

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  test:
    name: Run e2e Cypress tests on Node v18.x
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm install

      - name: Test cypress e2e
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm run dev
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          parallel: true
        env:
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Test cypress percy visual regression
        uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: "http://localhost:3000"
          browser: chrome
          command: npx percy exec -- cypress run --config video=false,screenshotOnRunFailure=false
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
