name: test-e2e

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  test:
    name: Run e2e Cypress tests on Node v18.x
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install

      - name: Test e2e
        run: npm run e2e:headless
