name: test-static

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    name: Build with Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build-prod

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run static tests on Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve Git history, needed to verify commits
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linting with eslint, stylelint and ls-lint
        run: npm run lint

      - name: Type checking
        run: npm run check-types
