name: test-unit

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  test:
    name: Run unit tests with Jest on Node v18.x
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install

      - name: Test unit
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
